# Generated by Django 4.1.7 on 2023-03-30 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, unique=True, upload_to='actions/photo_partner', verbose_name='Фотография')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='actions.action')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
