# Generated by Django 4.1.7 on 2023-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_action_video_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='preview',
            field=models.ImageField(default=None, unique=True, upload_to='actions/photo', verbose_name='Фотография'),
        ),
    ]
